parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: lotofootv2
    database_user: root
    database_password: 
    mailer_transport: gmail
    mailer_user: lotofoot.mail
    mailer_password: 
    mailer_from: lotofoot.mail@gmail.com
    url: http://localhost/lotofoot-v2/app_dev.php/
    locale: fr
    secret: 0151ce848a4a6366e413b01411cb4dee972c1051
    database_path: null
