security:
    encoders:
        Lotofootv2\Bundle\Entity\Account: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        user_db:
            entity: { class: Lotofootv2Bundle:Account, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false

        root_firewall:
            pattern:    ^/$
            security: false

        login_firewall:
            pattern:    ^/login$
            anonymous:  true

        public:
            pattern:  ^/(css|images|js|img)$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   _logout
                target: /
            #anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY}
