_root:
    resource: "@Lotofootv2Bundle/Controller/RootController.php"
    type:     annotation

_login:
    resource: "@Lotofootv2Bundle/Controller/LoginController.php"
    type:     annotation
    
_register:
    resource: "@Lotofootv2Bundle/Controller/RegisterController.php"
    type:     annotation

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_home:
    resource: "@Lotofootv2Bundle/Controller/User/HomeController.php"
    type:     annotation
    
_league_ranking:
    resource: "@Lotofootv2Bundle/Controller/User/League/RankingController.php"
    type:     annotation
    
_league_vote:
    resource: "@Lotofootv2Bundle/Controller/User/League/VoteController.php"
    type:     annotation

_admin_league:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueController.php"
    type:     annotation

_admin_league_day:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueDayController.php"
    type:     annotation

_admin_news:
    resource: "@Lotofootv2Bundle/Controller/Admin/NewsController.php"
    type:     annotation