_root:
    pattern:  /
    defaults: { _controller: Lotofootv2Bundle:Root:index }

_login:
    pattern:  /login
    defaults: { _controller: Lotofootv2Bundle:Login:index }

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_home:
    pattern:  /home
    defaults: { _controller: Lotofootv2Bundle:Home:index }

_admin_season:
    pattern:  /admin/season
    defaults: { _controller: Lotofootv2Bundle:Admin\Season:index }
    
_admin_season_create:
    pattern:  /admin/season/create
    defaults: { _controller: Lotofootv2Bundle:Admin\Season:create }

_admin_day:
    pattern:  /admin/day
    defaults: { _controller: Lotofootv2Bundle:Admin\Day:index }