_root:
    resource: "@Lotofootv2Bundle/Controller/RootController.php"
    type:     annotation

_login:
    resource: "@Lotofootv2Bundle/Controller/LoginController.php"
    type:     annotation
    
_register:
    resource: "@Lotofootv2Bundle/Controller/RegisterController.php"
    type:     annotation

_password_lost:
    resource: "@Lotofootv2Bundle/Controller/PasswordLostController.php"
    type:     annotation    

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_home:
    resource: "@Lotofootv2Bundle/Controller/User/HomeController.php"
    type:     annotation

_profile:
    resource: "@Lotofootv2Bundle/Controller/User/ProfileController.php"
    type:     annotation
    
_league_ranking:
    resource: "@Lotofootv2Bundle/Controller/User/League/RankingController.php"
    type:     annotation

_league_ranking_day:
    resource: "@Lotofootv2Bundle/Controller/User/League/RankingDayController.php"
    type:     annotation
    
_league_history:
    resource: "@Lotofootv2Bundle/Controller/User/League/HistoryController.php"
    type:     annotation
    
_league_vote:
    resource: "@Lotofootv2Bundle/Controller/User/League/VoteController.php"
    type:     annotation

_cl_admin:
    resource: "@Lotofootv2Bundle/Controller/Admin/CLController.php"
    type:     annotation

_cl_coming:
    resource: "@Lotofootv2Bundle/Controller/User/CL/ComingController.php"
    type:     annotation
    
_stats:
    resource: "@Lotofootv2Bundle/Controller/User/Stats/RewardsController.php"
    type:     annotation

_stats_teams:
    resource: "@Lotofootv2Bundle/Controller/User/Stats/TeamsController.php"
    type:     annotation

_admin_league:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueController.php"
    type:     annotation

_admin_league_day:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueDayController.php"
    type:     annotation

_admin_news:
    resource: "@Lotofootv2Bundle/Controller/Admin/NewsController.php"
    type:     annotation

_admin_users:
    resource: "@Lotofootv2Bundle/Controller/Admin/UsersController.php"
    type:     annotation

_rules:
    resource: "@Lotofootv2Bundle/Controller/User/League/RulesController.php"
    type:     annotation

_prizes:
    resource: "@Lotofootv2Bundle/Controller/User/League/PrizesController.php"
    type:     annotation

_cl_vote:
    resource: "@Lotofootv2Bundle/Controller/User/CL/VoteController.php"
    type:     annotation
    
_cl_board:
    resource: "@Lotofootv2Bundle/Controller/User/CL/BoardController.php"
    type:     annotation

_cl_rules:
    resource: "@Lotofootv2Bundle/Controller/User/CL/RulesController.php"
    type:     annotation

_cl_prizes:
    resource: "@Lotofootv2Bundle/Controller/User/CL/PrizesController.php"
    type:     annotation

 
_calendar:
    resource: "@Lotofootv2Bundle/Controller/User/CalendarController.php"
    type:     annotation
    
_forum:
    resource: "@Lotofootv2Bundle/Controller/ForumController.php"
    type:     annotation    
    
