_root:
    resource: "@Lotofootv2Bundle/Controller/RootController.php"
    type:     annotation

_login:
    resource: "@Lotofootv2Bundle/Controller/LoginController.php"
    type:     annotation
    
_register:
    resource: "@Lotofootv2Bundle/Controller/RegisterController.php"
    type:     annotation

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_home:
    resource: "@Lotofootv2Bundle/Controller/User/HomeController.php"
    type:     annotation
    
_league_ranking:
    resource: "@Lotofootv2Bundle/Controller/User/League/RankingController.php"
    type:     annotation
    
_league_history:
    resource: "@Lotofootv2Bundle/Controller/User/League/HistoryController.php"
    type:     annotation
    
_league_vote:
    resource: "@Lotofootv2Bundle/Controller/User/League/VoteController.php"
    type:     annotation
    
_stats:
    resource: "@Lotofootv2Bundle/Controller/User/Stats/RewardsController.php"
    type:     annotation

_admin_league:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueController.php"
    type:     annotation

_admin_league_day:
    resource: "@Lotofootv2Bundle/Controller/Admin/LeagueDayController.php"
    type:     annotation

_admin_news:
    resource: "@Lotofootv2Bundle/Controller/Admin/NewsController.php"
    type:     annotation

_rules:
    resource: "@Lotofootv2Bundle/Controller/User/League/RulesController.php"
    type:     annotation

_prizes:
    resource: "@Lotofootv2Bundle/Controller/User/League/PrizesController.php"
    type:     annotation
    
    
_calendar:
    resource: "@Lotofootv2Bundle/Controller/User/CalendarController.php"
    type:     annotation
    
_forum:
    resource: "@Lotofootv2Bundle/Controller/ForumController.php"
    type:     annotation    
    
_stats_teams:
    resource: "@Lotofootv2Bundle/Controller/StatsTeamsController.php"
    type:     annotation

_rewards:
    resource: "@Lotofootv2Bundle/Controller/RewardsController.php"
    type:     annotation
     
