_root:
    pattern:  /
    defaults: { _controller: Lotofootv2Bundle:Root:index }

_login:
    pattern:  /login
    defaults: { _controller: Lotofootv2Bundle:Login:index }

_login_check:
    pattern:  /login_check

_logout:
    pattern:  /logout

_home:
    pattern:  /home
    defaults: { _controller: Lotofootv2Bundle:User\Home:index }

_admin_league:
    pattern:  /admin/league
    defaults: { _controller: Lotofootv2Bundle:Admin\League:index }
    
_admin_league_create:
    pattern:  /admin/season/create
    defaults: { _controller: Lotofootv2Bundle:Admin\League:create }

_admin_day:
    pattern:  /admin/day
    defaults: { _controller: Lotofootv2Bundle:Admin\LeagueDay:index }