services:
    league_service:
        class:        "Lotofootv2\Bundle\Service\\LeagueService"
        arguments:    [@doctrine.orm.entity_manager, @logger]
    news_service:
        class:        "Lotofootv2\Bundle\Service\\NewsService"
        arguments:    [@doctrine.orm.entity_manager, @logger]
    account_service:
        class:        "Lotofootv2\Bundle\Service\\AccountService"
        arguments:    [@doctrine.orm.entity_manager, @logger]